version: "3"
networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=pgdb
    networks:
      - application
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=peon-db
    networks:
      - application
    container_name: pgdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
